# Generated by Django 4.1.1 on 2022-09-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=100)),
                ('fechaI', models.DateTimeField(max_length=100)),
                ('nombreProv', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
