# Generated by Django 4.1.1 on 2022-09-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaI',
            field=models.DateField(max_length=100),
        ),
    ]
