# Generated by Django 4.1.1 on 2022-09-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_producto_fechai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='nombreM',
        ),
    ]
