# Generated by Django 4.1.1 on 2022-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_fecha_producto_fechai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.DateField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('tipoPro', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
