# Generated by Django 4.1.1 on 2022-09-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_producto_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='nombre',
        ),
    ]
