# Generated by Django 4.1.1 on 2022-09-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_proveedor_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='Proveedor',
        ),
    ]
