# Generated by Django 4.1.1 on 2022-09-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_nombre_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
