# Generated by Django 4.1.1 on 2022-09-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_producto_proveedor_delete_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Proveedor',
            new_name='proveedor',
        ),
    ]
