# Generated by Django 4.1.1 on 2022-09-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='nombreProv',
        ),
    ]
