# Generated by Django 4.1.1 on 2022-09-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_proveedor_producto_nombreprov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombreProv',
        ),
    ]
