# Generated by Django 4.1.1 on 2022-09-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_producto_nombreprov'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
