# Generated by Django 4.1.1 on 2022-09-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
