# Generated by Django 4.1.1 on 2022-09-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_producto_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
