# Generated by Django 4.1.1 on 2022-09-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
