# Generated by Django 4.1.1 on 2022-10-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaI',
            field=models.DateField(),
        ),
    ]
