# Generated by Django 4.1 on 2022-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citas',
        ),
    ]
