# Generated by Django 4.1 on 2022-11-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(max_length=100)),
                ('Hora', models.TimeField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.CharField(max_length=100)),
                ('Mascota', models.CharField(max_length=100)),
            ],
        ),
    ]
