# Generated by Django 4.1 on 2022-11-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_citas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='Cliente',
            new_name='Cliente1',
        ),
        migrations.RenameField(
            model_name='citas',
            old_name='Mascota',
            new_name='Mascota1',
        ),
    ]
