# Generated by Django 4.1 on 2022-11-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_cliente_citas_cliente1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citas',
        ),
    ]
