# Generated by Django 4.1 on 2022-11-02 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(max_length=100)),
                ('Hora', models.TimeField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mascota')),
            ],
        ),
    ]
